### ISSUE TITLE
Sample目录里的例子跑不通

### ISSUE THREAD

**Issue by Rr7716** [limpo1989/kcp-csharp#29]
System.Net.Sockets.SocketException (10054): 远程主机强迫关闭了一个现有的连接。
   at System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   at KcpProject.UDPSession.Recv(Byte[] data, Int32 index, Int32 length) in C:\Users\Admin\Downloads\ConsoleApp2\UDPSession.cs:line 133
Receive Message failed.

没有动代码，跑不通，请问是什么原因呢

**Comment by limpo1989** [comment]
需要检查一下你的服务器是否正常，比如防火墙，端口，客户端连接地址
